name: Deploy to Hosting Server

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload via SFTP
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SFTP_HOST }}  # Replace with your SFTP server
          username: ${{ secrets.SFTP_USERNAME }}  # Replace with your SFTP username
          password: ${{ secrets.SFTP_PASSWORD }}  # Replace with your SFTP password
          port: 22  # SFTP default port
          source: "./"  # Local directory to upload
          target: "/public_html/"  # Replace with your server directory
